export { default as Home } from "./Home";
export { default as Explore } from "./Explore";
export { default as AllUsers } from "./AllUsers";
export { default as HomCreatePoste } from "./CreatePost";
export { default as EditPost } from "./EditPost";
export { default as PostDetaile } from "./PostDetaile";
export { default as Profile } from "./Profile";
export { default as Saved } from "./Saved";
export { default as UpdateProfile } from "./UpdateProfile";
